project:
  type: website

website:
  title: "Jamel Belgcem"
  page-footer:
    left: "Website made with [Quarto](https://quarto.org/)"
  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Posts
        href: index.qmd
      - icon: envelope
        href: mailto:jamelbelgacem@hotmail.com
      - icon: github
        href: https://github.com/JamBelg
      - icon: linkedin
        href: https://www.linkedin.com/in/jamel-belgacem-289606a7/
        
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

